USE [dw_db]
GO

SELECT  d.organization,
        d.organization, 
        d.organization_name, 
        d.home_department_code, 
        d.department_name, 
        d.card_type_description,
        d.card_key, 
        d.employee_id, 
        d.card_name, 
        d.name_comp, 
        d.ecch_orig_training_date, 
        d.ecch_training_date, 
        d.emp_status_cd, 
        d.date_issued, 
        d.status, 
        d.expiration_month, 
        d.expiration_year, 
        d.cancellation_date, 
        d.cancelled_by, 
        d.transaction_id, 
        d.transaction_date, 
        d.posted_date, 
        d.reference_number, 
        d.point_of_sales_code, 
        d.mcc_group_description, 
        d.vendor_mcc, 
        d.mcc_code_description, 
        ISNULL(d.vendor_id, i.vendor_id) AS vendor_id,
        d.vendor_tax_id, 
        d.vendor_name, 
        d.vendor_city, 
        d.vendor_state, 
        d.vendor_zip, 
        d.vendor_country,
        d.transaction_sequence,
        d.account_index,
        d.fund_code,
        d.organization_code,
        d.account_code,
        d.program_code,
        d.transaction_description, 
        d.comment, 
        d.use_tax_flag,
        i.line_item_sequence,
        i.line_item_description,
        i.commodity_code,
        i.supply_type,
        i.purchase_invoice_number,
        i.vendor_order_number,
        i.order_date,
        i.destination_zip,
        i.destination_country,
        d.transaction_split,
        i.line_item_split,
        CAST(d.transaction_split * i.quantity AS DECIMAL(19, 4)) AS quantity, 
        i.unit_of_measure, 
        CAST((d.transaction_split * d.transaction_amount)*(CASE WHEN i.line_item_split = 0 THEN 1 ELSE ISNULL(i.line_item_split,1) END/ISNULL(i.quantity,1)) AS DECIMAL(19,4)) AS net_unit_cost, 
        CAST((d.transaction_split * d.transaction_amount)*(CASE WHEN i.line_item_split = 0 THEN 1 ELSE ISNULL(i.line_item_split,1) END) AS DECIMAL(19,4)) AS line_item_amount, 
        d.transaction_amount, 
        d.total_transaction_amount
FROM    dbo.ec_purchase_line_item_SUM AS t 
        INNER JOIN  dbo.ec_purchase_line_item AS i ON t.transaction_id = i.transaction_id 
        RIGHT OUTER JOIN dbo.ec_purchase_trans_detail AS d ON i.transaction_id = d.transaction_id
        WHERE   d.transaction_date >= '2017-07-01' AND d.transaction_split<>1