USE [dw_db]
GO

SELECT  c.organization, 
        c.organization_name, 
        c.home_department_code, 
        c.department_name, 
        c.CARD_TYPE_DESCRIPTION AS card_type_description,
        c.card_key, 
        c.employee_id, 
        c.card_name, 
        c.name_comp, 
        c.ecch_orig_training_date, 
        c.ecch_training_date, 
        c.emp_status_cd, 
        c.date_issued, 
        c.status, 
        c.expiration_month, 
        c.expiration_year, 
        c.cancellation_date, 
        c.cancelled_by, 
        p.transaction_id, 
        p.transaction_date, 
        p.posted_date, 
        p.reference_number, 
        p.point_of_sales_code, 
        g.mcc_group_description, 
        p.vendor_mcc, 
        m.mcc_code_description, 
        d.vendor_id,
        p.vendor_tax_id, 
        p.vendor_name, 
        p.vendor_city, 
        p.vendor_state, 
        p.vendor_zip, 
        p.vendor_country,
        d.transaction_sequence,
        ISNULL(d.account_index,p.account_index) AS account_index,
        d.fund_code,
        d.organization_code,
        ISNULL(d.account_code, p.account_code) AS account_code,
        d.program_code,
        CAST(ISNULL(d.transaction_amount, p.transaction_amount) AS DECIMAL(19,4)) AS transaction_amount,
        d.use_tax_amount,
        CAST(ISNULL(d.transaction_amount, p.transaction_amount)/p.transaction_amount AS DECIMAL(19,4)) AS transaction_split,
        d.transaction_description, 
        d.comment, 
        d.use_tax_flag,
        p.calculated_use_tax_amount,
        p.posted_use_tax_amount,
        CAST(p.transaction_amount AS DECIMAL(19,4)) AS total_transaction_amount
FROM    pur.ec_cardholder AS c 
        RIGHT OUTER JOIN    dbo.mcc_group AS g  INNER JOIN   dbo.mcc_code AS m ON g.mcc_group = m.mcc_group 
        RIGHT OUTER JOIN    pur.ec_purchase AS p ON m.mcc_code = p.vendor_mcc 
        LEFT OUTER JOIN     pur.ec_trans_detail AS d ON p.transaction_id = d.transaction_id ON c.workgroup_key = p.workgroup_key AND c.card_key = p.card_key